openapi: 3.0.3
info:
  title: Library API
  version: 2.0.0
  description: STD22119 - STD22101
servers:
  - url: https://library.com
security:
  - OAuth2: [read] # Par défaut, l'accès public
paths:
  /books:
    get:
      tags:
        - "Books"
      summary: Get all books
      description: The returned books are ordered by updated datetime.
      operationId: getBooks
      parameters:
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/pageSize"
        - in: query
          name: bookName
          description: Filter return books by given name
          required: false
          schema:
            type: string
        - in: query
          name: startReleaseDate
          description: Filter books released on or after this date
          required: false
          schema:
            type: string
            format: date
        - in: query
          name: endReleaseDate
          description: Filter books released on or before this date
          required: false
          schema:
            type: string
            format: date
      responses:
        200:
          description: The list of filtered books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
        400:
          $ref: "#/components/responses/Response400"
        403:
          $ref: "#/components/responses/Response403"
        500:
          $ref: "#/components/responses/Response500"

    put:
      tags:
        - "Books"
      summary: Update multiple books
      description: Update information for multiple books
      requestBody:
        description: Import books in either Excel or JSON format
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Book"
          application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
            schema:
              $ref: "#/components/schemas/Book"
      responses:
        200:
          $ref: "#/components/responses/Response200"
        400:
          $ref: "#/components/responses/Response400"
        403:
          $ref: "#/components/responses/Response403"
        500:
          $ref: "#/components/responses/Response500"
  /authors:
    get:
      tags:
        - "Authors"
      summary: Get all authors
      description: Get all the authors in the database
      operationId: Get Authors
      parameters:
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/pageSize"
      responses:
        200:
          description: The list of Author
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Author"
        400:
          $ref: "#/components/responses/Response400"
        403:
          $ref: "#/components/responses/Response403"
        500:
          $ref: "#/components/responses/Response500"
    put:
      tags:
        - "Authors"
      summary: Update author by id
      description: Update information according to id
      parameters:
        - name: authorId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Import authors in either Excel or JSON format
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Author"
          application/vnd.openxmlformats-officedocument.spreadsheetml.sheet: # MIME type for Excel
            schema:
              $ref: "#/components/schemas/Author"
      responses:
        200:
          $ref: "#/components/responses/Response200"
        400:
          $ref: "#/components/responses/Response400"
        403:
          $ref: "#/components/responses/Response403"
        500:
          $ref: "#/components/responses/Response500"
    delete:
      tags:
        - "Authors"
      summary: Delete author by id
      description: Deleting an author by id
      parameters:
        - name: authorId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: "#/components/responses/Response200"
        400:
          $ref: "#/components/responses/Response400"
        403:
          $ref: "#/components/responses/Response403"
        500:
          $ref: "#/components/responses/Response500"
  /books/{bookId}/authors/{authorId}:
    put:
      tags:
        - "Books"
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: string
        - name: authorId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: "#/components/responses/Response200"
          description: The updated book
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
        400:
          $ref: "#/components/responses/Response400"
        403:
          $ref: "#/components/responses/Response403"
        500:
          $ref: "#/components/responses/Response500"
  /books/authors:
    put:
      tags:
        - "Books"
      summary: Update Book authors
      description: Update the authors of multiple books
      requestBody:
        description: Import books in either Excel or JSON format
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateBookAuthor"
          application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
            schema:
              $ref: "#/components/schemas/UpdateBookAuthor"
      responses:
        200:
          $ref: "#/components/responses/Response200"
        400:
          $ref: "#/components/responses/Response400"
        403:
          $ref: "#/components/responses/Response403"
        500:
          $ref: "#/components/responses/Response500"
  /books/import:
    post:
      tags:
        - "Books"
      summary: Import books
      description: Import a list of books
      operationId: importBooks
      security:
        - OAuth2: [write]
      requestBody:
        description: Import books in either Excel or JSON format
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookImport"
          application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
            schema:
              $ref: "#/components/schemas/ExcelBookImport"
      responses:
        200:
          description: List of imported books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
        400:
          $ref: "#/components/responses/Response400"
        403:
          $ref: "#/components/responses/Response403"
        500:
          $ref: "#/components/responses/Response500"
  /authors/import:
    post:
      tags:
        - "Authors"
      summary: Import authors
      description: Import a list of authors
      security:
        - OAuth2: [write]
      operationId: importAuthors
      requestBody:
        description: Import authors in either Excel or JSON format
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthorImport"
          application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
            schema:
              $ref: "#/components/schemas/ExcelAuthorImport"
      responses:
        200:
          description: List of imported authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Author"
        400:
          $ref: "#/components/responses/Response400"
        403:
          $ref: "#/components/responses/Response403"
        500:
          $ref: "#/components/responses/Response500"

  /loans:
    post:
      tags:
        - "Loans"
      summary: Borrow a book
      description: Record a book loan by a visitor
      security:
        - OAuth2: [write]
      requestBody:
        description: Loan details
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Loan"
      responses:
        200:
          $ref: "#/components/responses/Response200"
        400:
          $ref: "#/components/responses/Response400"
        403:
          $ref: "#/components/responses/Response403"
        500:
          $ref: "#/components/responses/Response500"
    put:
      tags:
        - "Loans"
      summary: Return a book
      description: Record the return of a borrowed book by a visitor
      security:
        - OAuth2: [write]
      requestBody:
        description: Return details
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Loan"
      responses:
        200:
          $ref: "#/components/responses/Response200"
        400:
          $ref: "#/components/responses/Response400"
        403:
          $ref: "#/components/responses/Response403"
        500:
          $ref: "#/components/responses/Response500"

  /loans/{loanId}:
    get:
      tags:
        - "Loans"
      summary: Get loan details by ID
      description: Get details about a specific loan
      operationId: getLoanById
      parameters:
        - name: loanId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: The loan details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Loan"
        400:
          $ref: "#/components/responses/Response400"
        403:
          $ref: "#/components/responses/Response403"
        500:
          $ref: "#/components/responses/Response500"

  /books/borrowed:
    get:
      tags:
        - "Books"
      summary: Get borrowed books
      description: Get the list of books currently borrowed
      security:
        - OAuth2: [write]
      responses:
        200:
          description: The list of borrowed books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
        400:
          $ref: "#/components/responses/Response400"
        403:
          $ref: "#/components/responses/Response403"
        500:
          $ref: "#/components/responses/Response500"

  /books/available:
    get:
      tags:
        - "Books"
      summary: Get available books
      description: Get the list of books currently available for borrowing
      security:
        - OAuth2: [read]
      responses:
        200:
          description: The list of available books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
        400:
          $ref: "#/components/responses/Response400"
        403:
          $ref: "#/components/responses/Response403"
        500:
          $ref: "#/components/responses/Response500"

  /visitors:
    get:
      tags:
        - "Visitors"
      summary: Get all visitors
      description: Get a list of all visitors
      operationId: getVisitors
      responses:
        200:
          description: The list of visitors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Visitor"
        400:
          $ref: "#/components/responses/Response400"
        403:
          $ref: "#/components/responses/Response403"
        500:
          $ref: "#/components/responses/Response500"

  /visitors/{visitorId}:
    get:
      tags:
        - "Visitors"
      summary: Get visitor by ID
      description: Get information about a specific visitor
      operationId: getVisitorById
      parameters:
        - name: visitorId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: The visitor details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Visitor"
        400:
          $ref: "#/components/responses/Response400"
        403:
          $ref: "#/components/responses/Response403"
        500:
          $ref: "#/components/responses/Response500"

  /visitors/{visitorId}/activities:
    get:
      tags:
        - "Visitors"
      summary: Get visitor activities
      description: Get the list of activities performed by a visitor within a specified period
      security:
        - OAuth2: [read]
      parameters:
        - name: visitorId
          in: path
          required: true
          schema:
            type: string
        - name: startDate
          in: query
          description: Start date of the period
          required: true
          schema:
            type: string
            format: date-time
        - name: endDate
          in: query
          description: End date of the period
          required: true
          schema:
            type: string
            format: date-time
      responses:
        200:
          description: The list of visitor activities
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/VisitorActivity"
        400:
          $ref: "#/components/responses/Response400"
        403:
          $ref: "#/components/responses/Response403"
        500:
          $ref: "#/components/responses/Response500"

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://auth-server.com/oauth/authorize
          scopes:
            read: Grants read access # public
            write: Grants write access # admin

  schemas:
    Book:
      allOf:
        - $ref: "#/components/schemas/CrupdateBook"
        - type: object
          properties:
            author:
              $ref: "#/components/schemas/Author"
            status:
              type: string
              enum:
                - AVAILABLE
                - BORROWED

    Author:
      type: object
      properties:
        authorId:
          type: string
        name:
          type: string
        sex:
          enum:
            - M
            - F
    CrupdateBook:
      type: object
      properties:
        bookId:
          type: string
        bookName:
          type: string
        pageNumbers:
          type: string
        topic:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER
        releaseDate:
          type: string
          format: date

    UpdateBookAuthor:
      type: object
      properties:
        bookId:
          type: string
        authorId:
          type: string

    AuthorImport:
      oneOf:
        - $ref: "#/components/schemas/ExcelAuthorImport"
        - $ref: "#/components/schemas/JSONAuthorImport"

    ExcelAuthorImport:
      $ref: "#/components/schemas/Author"

    JSONAuthorImport:
      $ref: "#/components/schemas/Author"

    BookImport:
      oneOf:
        - $ref: "#/components/schemas/ExcelBookImport"
        - $ref: "#/components/schemas/JSONBookImport"

    ExcelBookImport:
      $ref: "#/components/schemas/Book"

    JSONBookImport:
      $ref: "#/components/schemas/Book"

    defaultResponse:
      type: object
      properties:
        status:
          type: object
          properties:
            code:
              type: integer
            message:
              type: string
        body: {}

    Visitor:
      type: object
      properties:
        visitorId:
          type: string
        name:
          type: string
        reference:
          type: string
        activities:
          type: array
          items:
            type: object
            properties:
              activityType:
                type: string
                enum:
                  - BORROW
                  - RETURN
              bookId:
                type: string
              date:
                type: string
                format: date-time

    VisitorActivity:
      type: object
      properties:
        activityType:
          type: string
          enum:
            - BORROW
            - RETURN
        bookId:
          type: string
        date:
          type: string
          format: date-time

    Loan:
      type: object
      properties:
        loanId:
          type: string
        bookId:
          type: string
        loanDate:
          type: string
          format: date-time

  responses:
    Response200:
      description: HTTP 200 (OK)
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/defaultResponse"
          example:
            status:
              code: 200
              message: OK
    Response400:
      description: HTTP 400 (Bad Request)
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/defaultResponse"
          example:
            status:
              code: 400
              message: Bad Request
    Response403:
      description: HTTP 403 (Forbidden)
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/defaultResponse"
          example:
            status:
              code: 403
              message: Forbidden
    Response500:
      description: HTTP 500 (Internal Server Error)
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/defaultResponse"
          example:
            status:
              code: 500
              message: Internal Server Error

  parameters:
    page:
      in: query
      name: page
      schema:
        type: integer
        default: 1
      required: false
    pageSize:
      in: query
      name: pageSize
      schema:
        type: integer
        default: 50
      required: false